apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc 
  namespace: test
spec:
  storageClassName: vsphere-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

